### ISSUE TITLE
What if mariadb not accept my.cnf

### ISSUE THREAD

**Issue by smthakor1979** [flexcomng/erpnext_quick_install#1]
Make the necessary changes to the MariaDB configuration files.

# vi /etc/mysql/mariadb.conf.d/50-server.cnf
[mysqld]
innodb-file-format=barracuda
innodb-file-per-table=1
innodb-large-prefix=1
character-set-client-handshake = FALSE
character-set-server = utf8mb4
collation_server = utf8mb4_unicode_ci
And also comment out the following.

#character-set-server = utf8mb4
#collation-server = utf8mb4_general_ci
# vi /etc/mysql/mariadb.conf.d/50-client.cnf
[client]
default-character-set = utf8mb4
Restart MariaDB to apply the modifications.

# systemctl restart mariadb

**Comment by flexcomng** [comment]
Is there any particular reason why the MariaDB settings change is needed? the MariaDB file currently updated is /etc/mysql/my.cnf and it seems to work fine for all distros tested so I would like to know why this need to be changed.
