### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by TurkerTunali** [flexcomng/erpnext_quick_install#15]
It generates this:
```You should register before running non-interactively, or provide --agree-tos and --email <email_address> flags.```

You may want to add "--agree-tos" flag in an appropriate location.

Complete log:
Would you like to install SSL? (yes/no)
Response: yes
Make sure your domain name is pointed to the IP of this instance and is reachable before your proceed.
Enter your email address: ____@gmail.com
Installing Certbot...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
snapd is already the newest version (2.58+22.04.1).
snapd set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
core 16-2.61.1 from Canonical✓ installed
snap "core" has no updates available
certbot 2.9.0 from Certbot Project (certbot-eff✓) installed
Obtaining and installing SSL certificate...
nginx.conf already exists and this will overwrite it. Do you want to continue? [y/N]: $ sudo systemctl stop nginx
$ /usr/bin/certbot -n --config /etc/letsencrypt/configs/testogoz.logedo.com.cfg certonly
Saving debug log to /var/log/letsencrypt/letsencrypt.log
You should register before running non-interactively, or provide --agree-tos and --email <email_address> flags.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
$ sudo systemctl start nginx
There was a problem trying to setup SSL for your site
Setting Up cron job to Renew lets-encrypt every month
SSL certificate installed successfully.
--------------------------------------------------------------------------------
Congratulations! You have successfully installed ERPNext Version 14.
You can start using your new ERPNext installation by visiting https://testogoz.logedo.com
(if you have enabled SSL and used a Fully Qualified Domain Name
during installation) or http://10.80.99.15 to begin.
Install additional apps as required. Visit https://docs.erpnext.com for Documentation.
Enjoy using ERPNext!

**Comment by flexcomng** [comment]
@TurkerTunali Thanks for catching this omission. The necessary flags have been added.
