### ISSUE TITLE
issue running ERP v14 Development Enviromment

### ISSUE THREAD

**Issue by Chicken0Ghost** [flexcomng/erpnext_quick_install#19]
nic@homelab:~/frappe-bench$ bench start
07:57:46 system        | redis_cache.1 started (pid=8955)
07:57:46 system        | redis_queue.1 started (pid=8959)
07:57:46 redis_cache.1 | 8957:C 23 Apr 2024 07:57:46.011 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
07:57:46 redis_cache.1 | 8957:C 23 Apr 2024 07:57:46.011 # Redis version=6.0.16, bits=64, commit=00000000, modified=0, pid=8957, just started
07:57:46 redis_cache.1 | 8957:C 23 Apr 2024 07:57:46.011 # Configuration loaded
07:57:46 redis_cache.1 | 8957:M 23 Apr 2024 07:57:46.012 * Increased maximum number of open files to 10032 (it was originally set to 1024).
07:57:46 redis_cache.1 | 8957:M 23 Apr 2024 07:57:46.014 * Running mode=standalone, port=13000.
07:57:46 redis_cache.1 | 8957:M 23 Apr 2024 07:57:46.014 # Server initialized
07:57:46 redis_cache.1 | 8957:M 23 Apr 2024 07:57:46.014 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
07:57:46 redis_cache.1 | 8957:M 23 Apr 2024 07:57:46.015 * Ready to accept connections
07:57:46 system        | socketio.1 started (pid=8967)
07:57:46 system        | web.1 started (pid=8965)
07:57:46 redis_queue.1 | 8963:C 23 Apr 2024 07:57:46.020 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
07:57:46 redis_queue.1 | 8963:C 23 Apr 2024 07:57:46.021 # Redis version=6.0.16, bits=64, commit=00000000, modified=0, pid=8963, just started
07:57:46 redis_queue.1 | 8963:C 23 Apr 2024 07:57:46.021 # Configuration loaded
07:57:46 redis_queue.1 | 8963:M 23 Apr 2024 07:57:46.022 * Increased maximum number of open files to 10032 (it was originally set to 1024).
07:57:46 redis_queue.1 | 8963:M 23 Apr 2024 07:57:46.024 * Running mode=standalone, port=11000.
07:57:46 redis_queue.1 | 8963:M 23 Apr 2024 07:57:46.024 # Server initialized
07:57:46 redis_queue.1 | 8963:M 23 Apr 2024 07:57:46.024 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
07:57:46 redis_queue.1 | 8963:M 23 Apr 2024 07:57:46.025 * Ready to accept connections
07:57:46 system        | schedule.1 started (pid=8976)
07:57:46 system        | worker.1 started (pid=8977)
07:57:46 system        | watch.1 started (pid=8990)
07:57:46 watch.1       |
07:57:47 watch.1       | yarn run v1.22.22
07:57:47 watch.1       | $ node esbuild --watch --live-reload
07:57:48 web.1         | Illegal instruction (core dumped)
07:57:48 system        | web.1 stopped (rc=132)
07:57:48 system        | sending SIGTERM to redis_cache.1 (pid 8955)
07:57:48 system        | sending SIGTERM to redis_queue.1 (pid 8959)
07:57:48 system        | sending SIGTERM to socketio.1 (pid 8967)
07:57:48 system        | sending SIGTERM to watch.1 (pid 8990)
07:57:48 system        | sending SIGTERM to schedule.1 (pid 8976)
07:57:48 system        | sending SIGTERM to worker.1 (pid 8977)
07:57:48 redis_cache.1 | 8957:signal-handler (1713859068) Received SIGTERM scheduling shutdown...
07:57:48 redis_queue.1 | 8963:signal-handler (1713859068) Received SIGTERM scheduling shutdown...
07:57:48 system        | worker.1 stopped (rc=-15)
07:57:48 system        | schedule.1 stopped (rc=-15)
07:57:48 system        | socketio.1 stopped (rc=-15)
07:57:48 redis_cache.1 | 8957:M 23 Apr 2024 07:57:48.421 # User requested shutdown...
07:57:48 redis_cache.1 | 8957:M 23 Apr 2024 07:57:48.421 * Removing the pid file.
07:57:48 redis_cache.1 | 8957:M 23 Apr 2024 07:57:48.421 # Redis is now ready to exit, bye bye...
07:57:48 system        | redis_cache.1 stopped (rc=-15)
07:57:48 system        | watch.1 stopped (rc=-15)
07:57:48 redis_queue.1 | 8963:M 23 Apr 2024 07:57:48.431 # User requested shutdown...
07:57:48 redis_queue.1 | 8963:M 23 Apr 2024 07:57:48.431 * Removing the pid file.
07:57:48 redis_queue.1 | 8963:M 23 Apr 2024 07:57:48.432 # Redis is now ready to exit, bye bye...
07:57:48 system        | redis_queue.1 stopped (rc=-15)

and the error from worker.error.log:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/nic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/nic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/nic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/nic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/nic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/nic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.

this is on fresh ubnuntu 22.04 server not a vm, tried different install methods same issue.

runnig on ANCIENT HP prolint 380 G5

**Comment by kevinwaxi** [comment]
> nic@homelab:~/frappe-bench$ bench start
> 07:57:46 system        | redis_cache.1 started (pid=8955)
> 07:57:46 system        | redis_queue.1 started (pid=8959)
> 07:57:46 redis_cache.1 | 8957:C 23 Apr 2024 07:57:46.011 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> 07:57:46 redis_cache.1 | 8957:C 23 Apr 2024 07:57:46.011 # Redis version=6.0.16, bits=64, commit=00000000, modified=0, pid=8957, just started
> 07:57:46 redis_cache.1 | 8957:C 23 Apr 2024 07:57:46.011 # Configuration loaded
> 07:57:46 redis_cache.1 | 8957:M 23 Apr 2024 07:57:46.012 * Increased maximum number of open files to 10032 (it was originally set to 1024).
> 07:57:46 redis_cache.1 | 8957:M 23 Apr 2024 07:57:46.014 * Running mode=standalone, port=13000.
> 07:57:46 redis_cache.1 | 8957:M 23 Apr 2024 07:57:46.014 # Server initialized
> 07:57:46 redis_cache.1 | 8957:M 23 Apr 2024 07:57:46.014 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
> 07:57:46 redis_cache.1 | 8957:M 23 Apr 2024 07:57:46.015 * Ready to accept connections
> 07:57:46 system        | socketio.1 started (pid=8967)
> 07:57:46 system        | web.1 started (pid=8965)
> 07:57:46 redis_queue.1 | 8963:C 23 Apr 2024 07:57:46.020 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> 07:57:46 redis_queue.1 | 8963:C 23 Apr 2024 07:57:46.021 # Redis version=6.0.16, bits=64, commit=00000000, modified=0, pid=8963, just started
> 07:57:46 redis_queue.1 | 8963:C 23 Apr 2024 07:57:46.021 # Configuration loaded
> 07:57:46 redis_queue.1 | 8963:M 23 Apr 2024 07:57:46.022 * Increased maximum number of open files to 10032 (it was originally set to 1024).
> 07:57:46 redis_queue.1 | 8963:M 23 Apr 2024 07:57:46.024 * Running mode=standalone, port=11000.
> 07:57:46 redis_queue.1 | 8963:M 23 Apr 2024 07:57:46.024 # Server initialized
> 07:57:46 redis_queue.1 | 8963:M 23 Apr 2024 07:57:46.024 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
> 07:57:46 redis_queue.1 | 8963:M 23 Apr 2024 07:57:46.025 * Ready to accept connections
> 07:57:46 system        | schedule.1 started (pid=8976)
> 07:57:46 system        | worker.1 started (pid=8977)
> 07:57:46 system        | watch.1 started (pid=8990)
> 07:57:46 watch.1       |
> 07:57:47 watch.1       | yarn run v1.22.22
> 07:57:47 watch.1       | $ node esbuild --watch --live-reload
> 07:57:48 web.1         | Illegal instruction (core dumped)
> 07:57:48 system        | web.1 stopped (rc=132)
> 07:57:48 system        | sending SIGTERM to redis_cache.1 (pid 8955)
> 07:57:48 system        | sending SIGTERM to redis_queue.1 (pid 8959)
> 07:57:48 system        | sending SIGTERM to socketio.1 (pid 8967)
> 07:57:48 system        | sending SIGTERM to watch.1 (pid 8990)
> 07:57:48 system        | sending SIGTERM to schedule.1 (pid 8976)
> 07:57:48 system        | sending SIGTERM to worker.1 (pid 8977)
> 07:57:48 redis_cache.1 | 8957:signal-handler (1713859068) Received SIGTERM scheduling shutdown...
> 07:57:48 redis_queue.1 | 8963:signal-handler (1713859068) Received SIGTERM scheduling shutdown...
> 07:57:48 system        | worker.1 stopped (rc=-15)
> 07:57:48 system        | schedule.1 stopped (rc=-15)
> 07:57:48 system        | socketio.1 stopped (rc=-15)
> 07:57:48 redis_cache.1 | 8957:M 23 Apr 2024 07:57:48.421 # User requested shutdown...
> 07:57:48 redis_cache.1 | 8957:M 23 Apr 2024 07:57:48.421 * Removing the pid file.
> 07:57:48 redis_cache.1 | 8957:M 23 Apr 2024 07:57:48.421 # Redis is now ready to exit, bye bye...
> 07:57:48 system        | redis_cache.1 stopped (rc=-15)
> 07:57:48 system        | watch.1 stopped (rc=-15)
> 07:57:48 redis_queue.1 | 8963:M 23 Apr 2024 07:57:48.431 # User requested shutdown...
> 07:57:48 redis_queue.1 | 8963:M 23 Apr 2024 07:57:48.431 * Removing the pid file.
> 07:57:48 redis_queue.1 | 8963:M 23 Apr 2024 07:57:48.432 # Redis is now ready to exit, bye bye...
> 07:57:48 system        | redis_queue.1 stopped (rc=-15)
> 
> and the error from worker.error.log:
> 
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "/home/nic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
>     pubsub.get_message(ignore_subscribe_messages=True,
>   File "/home/nic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
>     response = self.parse_response(block=False, timeout=timeout)
>   File "/home/nic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
>     if not block and not conn.can_read(timeout=timeout):
>   File "/home/nic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
>     return self._parser.can_read(timeout)
>   File "/home/nic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 416, in can_read
>     return self.read_from_socket(timeout=timeout,
>   File "/home/nic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 429, in read_from_socket
>     raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
> redis.exceptions.ConnectionError: Connection closed by server.
> 
> this is on fresh ubnuntu 22.04 server not a vm, tried different install methods same issue.
> 
> runnig on ANCIENT HP prolint 380 G5

Which version of ERP are you trying to run ?

**Comment by Chicken0Ghost** [comment]
ERP V14

**Comment by Chicken0Ghost** [comment]
Ok Aprren
