### ISSUE TITLE
V13 & Assets / Js not found

### ISSUE THREAD

**Issue by medicall-labs** [flexcomng/erpnext_quick_install#2]
The V13 script edit is required and on processing the quick install the assets and js files missing in the login page and unable to login with the Administrator username and created password during the script execution.

**Comment by flexcomng** [comment]
@medicall-org Thanks for the feedback. The script was however designed and tested extensively for V14 install and was not tested for V13 so your experience using it for V13 installation may vary greatly as most of the packages and dependencies installed are for V14. While I believe it might be of some benefit to adapt it for V13 installation, that might require a great amount of effort for a past version and I personally recommend moving to V14 which is very stable and contains a slew of improvements to enhances the overall user experience.

**Comment by medicall-org** [comment]
Did change the version from 14 to 13  

`bench init frappe-bench --version version-13 --verbose --install-app erpnext --version version-13`

Ubuntu22.04 is the install environment . And it is a amd64 architecture

**Comment by medicall-labs** [comment]
@flexcomng  The main reason we choose V13 is for the Healthcare app , which I presume not available in V14 .

**Comment by flexcomng** [comment]
@medicall-labs All domains are available in v14. They are available as separate apps. To install Healthcare app in V14 after installing your site and ERPNext, go to your frappe-bench directory and use the following commands:

`bench get-app healthcare `
`bench --site [your-site-name] install-app healthcare`

This will install the healthcare app for you in V14. I intend adding post-production install options for installing additional apps based on your preference.

**Comment by medicall-labs** [comment]
@flexcomng  Thanks the above worked , but as mentioned earlier the css and js budle is not loading in login page and unable to login using the credentials .

**Comment by abrahamp47** [comment]
I am facing the same issue, havent made any version changes but the CSS and JS bundle isnt getting loaded any fix ?

**Comment by flexcomng** [comment]
@abrahamp47 @medicall-labs this is a permission issue. go to your user's home directory and run sudo chmod 755 /home/$(echo $USER). This should give the current user permission to all files and folders in the user's directory. Then go to your bench directory and run bench --site [your-site-name] migrate and bench restart.

**Comment by medicall-labs** [comment]
But still the error persists , It shows that the /home/$(echo $USER) directory is not available . Help me out in this regard .
