### ISSUE TITLE
Installer exits after entering Administrator password 

### ISSUE THREAD

**Issue by Rebaz-balisani** [flexcomng/erpnext_quick_install#21]
I've just come across this fine script. I noticed an issue trying to use this in Ubuntu 22; at the point where you insert the admin user passwords; the script causes Putty/bitvise to exit immediately with no warnings. There are no error messages but it happens after you enter the site name and admin password.
It happens on both:
1.contabo vps
2.local vms

**Comment by flexcomng** [comment]
This issue is same as the one referenced below so lets consolidate it and try to resolve it.
https://github.com/flexcomng/erpnext_quick_install/issues/20
