### ISSUE TITLE
frappe: ERROR (no such group)

### ISSUE THREAD

**Issue by eldonpZA** [flexcomng/erpnext_quick_install#24]
yarn run v1.22.22
$ node esbuild --production --apps erpnext --run-build-command
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
File                                                        Size

erpnext/dist/js/
├─ bank-reconciliation-tool.bundle.ALGDCWUD.js              17.17 Kb
├─ erpnext-web.bundle.J4A2DQB4.js                           0.29 Kb
├─ erpnext.bundle.URHHQOIR.js                               219.22 Kb
├─ item-dashboard.bundle.4SC3ZMD4.js                        10.24 Kb
├─ point-of-sale.bundle.CAHAJRAW.js                         92.61 Kb
└─ bom_configurator.bundle.D2UVDA3I.js                      8.63 Kb

erpnext/dist/css/
├─ erpnext-web.bundle.FYOSXMT6.css                          2.86 Kb
├─ erpnext.bundle.CP5ORPFC.css                              44.14 Kb
└─ erpnext_email.bundle.IBT5S2AJ.css                        0.56 Kb

erpnext/dist/css-rtl/
├─ erpnext-web.bundle.LEPVNSWL.css                          2.87 Kb
├─ erpnext.bundle.B2TKEDAR.css                              44.13 Kb
└─ erpnext_email.bundle.G4EBAOJW.css                        0.56 Kb

 DONE  Total Build Time: 6.301s

 WARN  Cannot connect to redis_cache to update assets_json
 WARN  Cannot connect to redis_cache to update assets_json
 WARN  Cannot connect to redis_cache to update assets_json
Done in 10.91s.
Compiling translations for erpnext
$ sudo supervisorctl restart frappe:
frappe: ERROR (no such group)
frappe: ERROR (no such group)
WARN: restarting supervisor group `frappe:` failed. Use `bench restart` to retry.

**Comment by flexcomng** [comment]
@eldonpZA  This is a standerd error during site install. This is taken care of further down the script actions. so unless the installation process terminates, you should allow the script to continue.

**Comment by eldonpZA** [comment]
Thanks
