### ISSUE TITLE
Suggestion for Python "externally managed" issue

### ISSUE THREAD

**Issue by Elkanaaa** [flexcomng/erpnext_quick_install#26]
It appears the Python marker file that's removed by this script - /usr/lib/python3.11/EXTERNALLY-MANAGED - (or /usr/lib/python3.12/EXTERNALLY-MANAGED) can reappear. Probably through an update. This can cause a "surprise" with any future use of the pip3 command - such as an update of bench itself - "sudo pip3 install --upgrade frappe-bench".

You might consider using "sudo python3 -m pip config --global set global.break-system-packages true" instead of removing marker file.

I included it in a copy of this install script - after deleting the bit about “# Check if EXTERNALLY-MANAGED file exists and remove it”.

`So the copy I used now looks:

334  # Install bench
335  echo -e "${YELLOW}Now let's install bench${NC}"
336  sleep 2
337
338  sudo python3 -m pip config --global set global.break-system-packages true
339
340  sudo apt install python3-pip -y
341  sudo pip3 install frappe-bench
342
343  # Initiate bench in frappe-bench folder, but get a supervisor can't restart bench error...`

I've only run this once on 24.04. It installed to production without problem.

See also:
https://discuss.frappe.io/t/fully-automated-install-script-for-erpnext-version-14/104751/72

**Comment by flexcomng** [comment]
This has been implemented.
