### ISSUE TITLE
Proxmox Container with Ubuntu 22.04 LTS image - No website appears on installation completion

### ISSUE THREAD

**Issue by cgiakmoz** [flexcomng/erpnext_quick_install#3]
Hi, Is this script still actively maintained?

I wonder if there is any active preparation necessary to make it work.... (Other than 
$> apt update && apt upgrade.     )

For example:
-  Is it okay to run the script as root ? Perhaps I should create a user like "erpnext" first, and run install.sh from there ?
-  Should I be pre-installing LEMP or LAMP features?  I notice that, once completed, there is NO listed Webserver like NGINX or Apache in the list of installed ... for example if I type:
$>  systemctl
No webserver appears either installed OR active in the list!

**Comment by flexcomng** [comment]
The script is actively maintained and you typically do not need to do anything except run update and upgrade and reboot (if you're using Ubuntu 22.04).

You SHOULD NOT run the script as root. just follow the instructions on the readme.

The script installs all the necessary prerequisites and dependencies for ERPNext to run so you do not need any package installed before running the script. 

ERPNext uses NGINX web server and this is installed as part of Frappe's code execution process.
