### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by yahyaoudra** [flexcomng/erpnext_quick_install#5]
First of all thank you for this solution.

I tried to install ERPnext using it for testing purposes.
and it seems something didn't went well.

I used a  4 GB Memory / 80 GB Disk / LON1 - Ubuntu 22.04 (LTS) x64 Server by Digital Ocean.
I choose V15 
I completed the process and seems the installer got some issues during the installation.
 like one that says " no such directory /root"

But anyway at the end I'm getting this 

![Screenshot 2023-11-18 at 03 23 03](https://github.com/flexcomng/erpnext_quick_install/assets/67019341/62ddf100-c3ac-4c63-b00f-acda65022949)

**Comment by flexcomng** [comment]
did you create a standard user with sudo privileges or did you run the script as root?
