### ISSUE TITLE
v15 installation issues

### ISSUE THREAD

**Issue by washaqq** [flexcomng/erpnext_quick_install#8]
Hello
i installed on Ubuntu 22.04 it did not give me any error during installation, at the end it gave me success message but, it did not work, simply didnt work.
currentsite.txt is not created and i restarted bench with ```bench restart``` command here is what i get

``` $ supervisorctl restart frappe-bench-workers: frappe-bench-web:
frappe-bench-workers:frappe-bench-frappe-schedule: stopped
frappe-bench-workers:frappe-bench-frappe-short-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-long-worker-0: stopped
frappe-bench-web:frappe-bench-frappe-web: stopped
frappe-bench-workers:frappe-bench-frappe-schedule: started
frappe-bench-workers:frappe-bench-frappe-short-worker-0: started
frappe-bench-workers:frappe-bench-frappe-long-worker-0: started
frappe-bench-web:frappe-bench-node-socketio: ERROR (spawn error)
frappe-bench-web:frappe-bench-frappe-web: started
ERROR: supervisorctl restart frappe-bench-workers: frappe-bench-web:
subprocess.CalledProcessError: Command 'supervisorctl restart frappe-bench-workers: frappe-bench-web:' returned non-zero exit status 7.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/bench/cli.py", line 132, in cli
    bench_command()
  File "/usr/local/lib/python3.10/dist-packages/bench/commands/utils.py", line 41, in restart
    Bench(".").reload(web, supervisor, systemd)
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bench/bench.py", line 152, in reload
    restart_supervisor_processes(bench_path=self.name, web_workers=web, _raise=_raise)
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/bench.py", line 321, in restart_supervisor_processes
    failure = bench.run(f"{sudo}supervisorctl restart {group}", _raise=_raise)
  File "/usr/local/lib/python3.10/dist-packages/bench/bench.py", line 48, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd, _raise=_raise)
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/__init__.py", line 158, in exec_cmd
    raise CommandFailedError(cmd) from subprocess.CalledProcessError(return_code, cmd)
bench.exceptions.CommandFailedError: supervisorctl restart frappe-bench-workers: frappe-bench-web:
```

**Comment by washaqq** [comment]
Ok, seems like i won't get ant respond, but i will note my proceedings.
i think this script doesn't work right on newly fresh installed systems, too many things to install, update and upgrade that can not be configured all at the same time even you run update and upgrade command before you start running the script.
so i deleted frappe_bench folder and re-run the script, i will see what is next, and i will keep informing you.

**Comment by flexcomng** [comment]
@washaqq Your first attempt most likely resulted in an error somewhere during the process, which went unnoticed. The  What I recommend when this happens is exactly what you have already done, so watch out for the process and see if any error is displayed during the installation process.

The script doesn't currently handle errors when they occur during installation so your first attempt could have resulted in an error which you may not have noticed. A newer version of the script is currently in the works with significant error handling capabilities. The new version will be deployed as soon as all stability tests are completed.

**Comment by flexcomng** [comment]
@washaqq your last attempt failed because of the changes in this file /etc/supervisor/supervisord.conf which suggests that the installation was successful. please run` bench doctor` in your frappe-bench directory and let me know if bench is running.

**Comment by washaqq** [comment]
> @washaqq your last attempt failed because of the changes in this file /etc/supervisor/supervisord.conf which suggests that the installation was successful. please run` bench doctor` in your frappe-bench directory and let me know if bench is running.

@flexcomng 
here is the result; 
```
-----Checking scheduler status-----
Workers online: 2
-----None Jobs-----
```

**Comment by flexcomng** [comment]
Can you try to access your site?

**Comment by washaqq** [comment]
> Can you try to access your site?

i access the site after i saw the message, it seems working now, so what is the problem that it did not work on first and second try?

**Comment by washaqq** [comment]
> I'm happy your installation is now working. As I said earlier, because the script currently does not log errors, it is difficult to say what exactly could have happened without actually monitoring the installation process. My best guess at this point is package installation failure which prevented the site from installing successfully the first time. The new version of the script, when released, will solve this loophole.

thank you for this great script, even i have problems, it took less than the other manuel installation. Can't wait the new release.
